M48
; DRILL file {KiCad 7.0.1} date Mon Dec 25 09:53:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-25T09:53:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X3.4843Y-3.3622
X3.4843Y-3.5354
T2
X3.3858Y-3.9409
T3
X3.4055Y-2.4409
X3.4055Y-5.1575
X5.3543Y-4.0748
T0
M30
